version: '2'

services:

### PHP-FPM Container #######################################
  php-fpm:
    build:
      context: ./config/php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_MSMTP=${PHP_FPM_INSTALL_MSMTP}
        - EMAIL_SERVICE_URL=${EMAIL_SERVICE_URL}
        - MSMTP_DOMAIN=${POSTFIX_DOMAIN}
    ports:
      - "${PHP_FPM_SSH_PORT}:22"

### SSL ##################################
  ssl:
    build:
      context: ./config/ssl
    environment:
      - SSL_SUBJECT=${SSL_SUBJECT}
      - SSL_DNS=${SSL_DNS}

### Nginx Server Container ##################################
  nginx:
    build:
      context: ./config/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"

### Logrotate Container ####################################
  logrotate:
    image: tutum/logrotate:latest
    restart: on-failure:5
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

### Networks Setup ############################################
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
